version: '3.9'

services:

  # Database. Only Postgres is currently supported.
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
  
  # Redis with Redisearch.
  redis:
    image: redislabs/redisearch:latest

  # The API.
  # Check https://github.com/Shock-Link/API for the latest configuration settings.
  api:
    image: ghcr.io/shock-link/api:latest
    depends_on:
      - db
      - redis
    ports:
      - "5001:80/tcp"
    environment:
      - SHOCKLINK__DB=Host=docker-node;Port=1337;Database=root;Username=root;Password=root;Search Path=ShockLink
      - SHOCKLINK__REDIS__HOST=redis
      - SHOCKLINK__FRONTENDBASEURL=http://local:5002
  
  # The Web UI (this repository).
  webui:
    image: ghcr.io/redmushie/webui:master
    depends_on:
      - api
    ports:
      - "5002:80/tcp"
    environment:
      - SHOCKLINK_API_URL=http://local:5001/
      - SHOCKLINK_WEBUI_URL=http://local:5002/#/
      - SHOCKLINK_SHARE_URL=http://local:5002/#/public/proxy/shares/links/
