version: '3.9'

services:

  # Database. Only Postgres is currently supported.
  db:
    image: postgres:16
    ports:
      - "5432:5432/tcp"
    environment:
      - POSTGRES_PASSWORD=postgres
  
  # Redis with Redisearch.
  redis:
    image: redis/redis-stack-server:latest
    volumes:
      - /opt/docker/openshock/redis/redis-stack.conf:/redis-stack.conf
  
  # The API.
  # Check https://github.com/OpenShock/API for the latest configuration settings.
  api:
    image: ghcr.io/openshock/api:latest
    container_name: api
    depends_on:
      - db
      - redis
    ports:
      - "5001:80/tcp"
    environment:
      - SHOCKLINK__DB=Host=db;Port=5432;Database=postgres;Username=postgres;Password=postgres;Search Path=ShockLink
      - SHOCKLINK__REDIS__HOST=redis
      - SHOCKLINK__FRONTENDBASEURL=http://local:5002
  
  # The Web UI (this repository).
  webui:
    # Make sure to fresh build if you make changes:
    #     docker-compose up --build
    build: .
    container_name: webui
    depends_on:
      - api
    ports:
      - "5002:80/tcp"
    environment:
      - OPENSHOCK_NAME=LocalShock
      - OPENSHOCK_URL=http://webui.localhost:5002
      - OPENSHOCK_API_URL=http://api.localhost:5001
      - OPENSHOCK_SHARE_URL=http://webui.localhost:5002/#/public/proxy/shares/links/
