on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, reopened, synchronize]

name: ci-master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/.cache/pip
      #       ~/.platformio/cache
      #     key: ${{ runner.os }}-arch

      - uses: actions/setup-node@v3
        with:
          node-version: 17.x

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present
